# Generated by Django 2.2.3 on 2019-07-30 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Final_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='City',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Dammam', 'Dammam')], default='Riyadh', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Hospital',
            field=models.CharField(choices=[('King Faisal Hospital', 'King Faisal Hospital'), ('King Fahad Hospital', 'King Fahad Hospital'), ('King Khaled Hospital', 'King Khaled Hospital'), ('King Saud Hospital', 'King Saud Hospital')], default='King Saud Hospital', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='clinic',
            field=models.CharField(choices=[('Dintistry', 'Dintistry'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('General Medicine', 'General Medicine'), ('Surgery', 'Surgery'), ('Physical Therapy', 'Physical Therapy'), ('Neurologists', 'Neurologists'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=100),
        ),
    ]
