# Generated by Django 2.2.3 on 2019-07-31 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Final_App', '0003_doctors_av_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='av_date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='doctors',
            name='to_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
