# Generated by Django 2.2.3 on 2019-08-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_App', '0004_auto_20190731_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booking',
            field=models.CharField(default='not booking', max_length=100),
            preserve_default=False,
        ),
    ]
