# Generated by Django 2.2.3 on 2019-08-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_App', '0005_profile_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='bookings',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
