# Generated by Django 2.2.3 on 2019-08-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_App', '0006_doctors_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
